# Pytest configuration file
# Defines default execution settings, logging configuration and custom markers

[pytest]

addopts =
    -n 1
    --reruns 1
    --self-contained-html

# Enable live logging in terminal
log_cli = true
log_cli_level = INFO

# Custom markers used in the framework
markers =
    smoke: smoke test cases
    regression: regression test cases